Project 4: TSE Code Review
simoxsimo/2014Apple.com pull request #2
Opened 2019-12-10 21:37 UTC by simoxsimo

# Apple.com Clone

In this project I have done the following:
- Recreating the site's Layout using Flexbox.
- Using gradients on the NavBar.
- Adding images as backgrounds and using _"background-position"_ to move throughout the image.

2019-12-10 21:42 UTC, Anna-Myzukina commented
#### Pull Request under the review by Anna Muzykina (TSE)

2019-12-10 22:33 UTC, Anna-Myzukina commented
### Hi Mohammed!

### Nice job! Project looks! :+1: WOW  the readme file is very descriptive!

### But your project still needs changes.

- Kindly recommended checking HTML markup with this validator https://validator.w3.org/#validate_by_upload.

![ ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png)

Now it shows errors in your project

![errors](https://user-images.githubusercontent.com/26605804/70573073-d5e1f600-1ba9-11ea-9a26-4e9ab4382906.png)


- Please check linter, as I can see it doesn`t work now. You can read more here [Set up a code linter.](https://github.com/microverseinc/linters-config/tree/master/css)

![Screenshot from 2019-12-11 00-27-43](https://user-images.githubusercontent.com/26605804/70574575-18f19880-1bad-11ea-9798-2e66eb6265b8.png)


- Bottom contains four elements but they should be links (to another articles or #) ([link to page](https://web.archive.org/web/20140301004610/http://www.apple.com/))
![img](https://user-images.githubusercontent.com/26605804/70574420-be583c80-1bac-11ea-85f9-48cdc1c39d35.png)

- Please fix footer 

In original version footer is under the bottom
![footer](https://user-images.githubusercontent.com/26605804/70574703-60782480-1bad-11ea-9582-c4a61967ef8c.png)

In your version of the [Apple website](https://web.archive.org/web/20140301004610/http://www.apple.com/) webpage footer is in wrong place
![foot](https://user-images.githubusercontent.com/26605804/70574712-65d56f00-1bad-11ea-98c0-758159f74c85.png)

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

2019-12-10 22:34 UTC, Anna-Myzukina requested changes
The project needs changes

2019-12-10 22:37 UTC, Anna-Myzukina commented on index.html
> +						<img alt="otherImg4" src="images/otherImgs4.jpg">
This four elements should be links (to another articles or `#`)

2019-12-11 13:42 UTC, simoxsimo commented
Pull Request Closed to fix Stickler config

2019-12-11 13:42 UTC, closed without merging